#!/bin/sh

# shutdown all system-wide icewm  programs
for file in /etc/icewm/shutdown_d/*; do
  userfile=~/.icewm/shutdown_d/`echo $file | sed -e 's,/etc/icewm/shutdown_d/,,'`
  # root can disable autostart removing 'execute' bits
  if [ -x $file ]; then 
    [ -e $userfile ] || . $file
  fi
done

for file in ~/.icewm/shutdown_d/*; do
  # running user files 
  # user can disable autostart removing 'execute' bits
  [ -x $file ] && . $file
done

sync
sleep 2

if [ -e /run/systemd/system ]; then
    systemctl poweroff
else
    poweroff
fi
